name: Cypress Tests
on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
            path: |
              ~/.cache/Cypress
              node_modules
            key: ${{ runner.os }}-cypress-${{ hashFiles('package-lock.json') }}
          
      - name: Install Dependencies
        run: npm ci

      - name: Run Cypress Tests
        run: npx cypress run --record false --browser chrome --headless

      - name: Generate HTML Report
        if: always()
        run: |
          npm install mochawesome-merge
          npx mochawesome-merge cypress/reports/mocha/*.json > cypress/reports/mochareport.json
          npm install mochawesome-report-generator
          npx marge cypress/reports/mochareport.json -o cypress/reports/html --reportPageTitle "Cypress Report"

      - name: Archive Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-report
          path: cypress/reports/html

      - name: Deploy to GitHub Pages
        if: success() || failure()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: cypress/reports/html
          keep_files: true