name: Cypress Tests
on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    permissions:  # Add this section
      contents: write
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/Cypress
            node_modules
          key: ${{ runner.os }}-cypress-${{ hashFiles('package-lock.json') }}

      - name: Install Dependencies
        run: npm ci

      - name: Run Cypress Tests
        run: npx cypress run --browser chrome --headless || true

      - name: Generate HTML Report
        if: always()
        run: |
          npx mochawesome-merge cypress/reports/mocha/*.json > cypress/reports/mochareport.json
          npx marge cypress/reports/mochareport.json \
            -o cypress/reports/html \
            --reportPageTitle "Cypress Report" \
            --reportFilename index  # Force index.html name

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-report
          path: |
                cypress/reports/html
                cypress/reports/screenshots

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./cypress/reports/html
            destination_dir: ./  # Add this line
            force_orphan: true   # Clean previous deployments
            full_commit_message: "Deploy Cypress Report: ${{ github.sha }}"